version: "3.8"
services:
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 127.0.0.1:${POSTGRES_REMOTE_PORT}:5432
    # restart: always

  scrapper:
    build: .
    command: sh -c "poetry run python main.py"
    depends_on:
      - db

volumes:
  db_data:
